# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word'),
            preserve_default=False,
        ),
    ]
