# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20170210_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Category'),
            preserve_default=False,
        ),
    ]
