# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='word',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
