# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20170210_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='views',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='views',
            new_name='comments',
        ),
    ]
