# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20170210_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='url_text',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
