# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_word_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='url_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
