# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20170211_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='url_text',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
