# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_auto_20170211_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='url_text',
        ),
    ]
