# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_remove_word_url_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='url_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
