# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_word_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
